- name: claude-3-5-haiku
  modelId: us.anthropic.claude-3-5-haiku-20241022-v1:0
  modelUrl: "http://{{ .Release.Namespace }}.genai-hub-service.svc.cluster.local:443/anthropic/deployments/claude-3-5-haiku"
  redirectUrl: "{{ .Values.DemoAwsBedrockURL }}/anthropic/deployments/claude-3-5-haiku"
  provider: anthropic
  infrastructure: aws
  capabilities:
    completions: false
    embeddings: false
    image-generation: false
