- name: claude-haiku-4-5
  modelId: anthropic.claude-haiku-4-5-20251001-v1:0
  modelUrl: "http://{{ .Release.Namespace }}.genai-hub-service.svc.cluster.local:443/anthropic/deployments/claude-haiku-4-5"
  redirectUrl: "{{ .Values.DemoAwsBedrockURL }}/anthropic/deployments/claude-haiku-4-5"
  provider: anthropic
  infrastructure: aws
  capabilities:
    completions: false
    embeddings: false
    image-generation: false
