- name: gemini-1.5-flash
  modelId: ""
  modelUrl: "http://{{ .Release.Namespace }}.genai-hub-service.svc.cluster.local:443/google/deployments/gemini-1.5-flash"
  redirectUrl: "{{ .Values.DemoGcpVertexURL }}/google/deployments/gemini-1.5-flash"
  provider: google
  creator: google
  targetAPI: "/chat/completions"
  path: "/google/deployments/gemini-1.5-flash/chat/completions"
  infrastructure: gcp
  capabilities:
    completions: false
    embeddings: false
    image-generation: false
