- name: gpt-5-chat
  modelId: ""
  modelUrl: "http://{{ .Release.Namespace }}.genai-hub-service.svc.cluster.local:443/openai/deployments/gpt-5-chat"
  redirectUrl: "{{ .Values.GenAIURL }}/openai/deployments/gpt-5-chat"
  provider: openai
  creator: openai
  targetAPI: "/chat/completions"
  path: "/openai/deployments/gpt-5-chat/chat/completions"
  infrastructure: azure
  capabilities:
    completions: true
    embeddings: false
