- name: imagen-3-fast
  modelId: imagen-3.0-fast-generate-001
  modelUrl: "http://{{ .Release.Namespace }}.genai-hub-service.svc.cluster.local:443/google/deployments/imagen-3-fast"
  redirectUrl: "{{ .Values.DemoGcpVertexURL }}/google/deployments/imagen-3-fast"
  provider: google
  creator: google
  targetAPI: "/images/generations"
  path: "/google/deployments/imagen-3-fast/images/generations"
  infrastructure: gcp
  capabilities:
    completions: false
    embeddings: false
    image-generation: false
