- name: text-embedding-3-large
  modelId: ""
  modelUrl: "http://{{ .Release.Namespace }}.genai-hub-service.svc.cluster.local:443/openai/deployments/text-embedding-3-large"
  redirectUrl: "{{ .Values.GenAIURL }}/openai/deployments/text-embedding-3-large"
  provider: openai
  infrastructure: azure
  capabilities:
    chat-completion: false
    embeddings: true
