---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: private-model-config
  labels:
    {{- include "pegaTags" . | nindent 4 }}
spec:
  # SecretStoreRef defines which SecretStore to use when fetching the secret data
  secretStoreRef:
    name: cloudk-store
    kind: ClusterSecretStore  # or SecretStore
  refreshInterval: "1h0m0s"
  target:
    name: private-model-config
  dataFrom:
    - find:
        path: "genai_private_model/{{ .Values.ClusterGUID }}/model"
        name:
          regexp: .*