// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAda is an autogenerated mock type for the Ada type
type MockAda struct {
	mock.Mock
}

type MockAda_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAda) EXPECT() *MockAda_Expecter {
	return &MockAda_Expecter{mock: &_m.Mock}
}

// GetEmbedding provides a mock function with given fields: ctx, chunk
func (_m *MockAda) GetEmbedding(ctx context.Context, chunk string) ([]float32, int, error) {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedding")
	}

	var r0 []float32
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, int, error)); ok {
		return rf(ctx, chunk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, chunk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, chunk)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, chunk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAda_GetEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedding'
type MockAda_GetEmbedding_Call struct {
	*mock.Call
}

// GetEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk string
func (_e *MockAda_Expecter) GetEmbedding(ctx interface{}, chunk interface{}) *MockAda_GetEmbedding_Call {
	return &MockAda_GetEmbedding_Call{Call: _e.mock.On("GetEmbedding", ctx, chunk)}
}

func (_c *MockAda_GetEmbedding_Call) Run(run func(ctx context.Context, chunk string)) *MockAda_GetEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAda_GetEmbedding_Call) Return(_a0 []float32, _a1 int, _a2 error) *MockAda_GetEmbedding_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAda_GetEmbedding_Call) RunAndReturn(run func(context.Context, string) ([]float32, int, error)) *MockAda_GetEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAda creates a new instance of MockAda. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAda(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAda {
	mock := &MockAda{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
