// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmbedder is an autogenerated mock type for the Embedder type
type MockEmbedder struct {
	mock.Mock
}

type MockEmbedder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbedder) EXPECT() *MockEmbedder_Expecter {
	return &MockEmbedder_Expecter{mock: &_m.Mock}
}

// GetEmbedding provides a mock function with given fields: ctx, chunk
func (_m *MockEmbedder) GetEmbedding(ctx context.Context, chunk string) ([]float32, int, error) {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedding")
	}

	var r0 []float32
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, int, error)); ok {
		return rf(ctx, chunk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, chunk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, chunk)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, chunk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockEmbedder_GetEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedding'
type MockEmbedder_GetEmbedding_Call struct {
	*mock.Call
}

// GetEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk string
func (_e *MockEmbedder_Expecter) GetEmbedding(ctx interface{}, chunk interface{}) *MockEmbedder_GetEmbedding_Call {
	return &MockEmbedder_GetEmbedding_Call{Call: _e.mock.On("GetEmbedding", ctx, chunk)}
}

func (_c *MockEmbedder_GetEmbedding_Call) Run(run func(ctx context.Context, chunk string)) *MockEmbedder_GetEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmbedder_GetEmbedding_Call) Return(_a0 []float32, _a1 int, _a2 error) *MockEmbedder_GetEmbedding_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEmbedder_GetEmbedding_Call) RunAndReturn(run func(context.Context, string) ([]float32, int, error)) *MockEmbedder_GetEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with no fields
func (_m *MockEmbedder) GetURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEmbedder_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockEmbedder_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
func (_e *MockEmbedder_Expecter) GetURL() *MockEmbedder_GetURL_Call {
	return &MockEmbedder_GetURL_Call{Call: _e.mock.On("GetURL")}
}

func (_c *MockEmbedder_GetURL_Call) Run(run func()) *MockEmbedder_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbedder_GetURL_Call) Return(_a0 string) *MockEmbedder_GetURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbedder_GetURL_Call) RunAndReturn(run func() string) *MockEmbedder_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbedder creates a new instance of MockEmbedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbedder {
	mock := &MockEmbedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
