/*
 * Copyright (c) 2024 Pegasystems Inc.
 * All rights reserved.
 */

plugins {
    id("com.pega.dockercli.image")
}

project.ext["serviceName"] = "genai-vector-store-background"

// Define bitbucketUser and bitbucketPassword in  ~/.gradle/gradle.properties
// You can use  HTTP token instead of Password,
// HTTP token can be generated on git.pega.com (Under "Manage Account" -> "HTTP access tokens")
val bitbucketUser: String by project
val bitbucketPassword: String by project
val githubUser: String by project
val githubPassword: String by project

var isCI = System.getenv("CI") ?: "false"
var bitbucketUsr: String = System.getenv("BITBUCKET_USR") ?: bitbucketUser
var bitbucketPwd: String = System.getenv("BITBUCKET_PSW") ?: bitbucketPassword
var githubUsr: String = System.getenv("GITHUB_USR") ?: githubUser
var githubPwd: String = System.getenv("GITHUB_PSW") ?: githubPassword

tasks.buildImage.configure {
    buildArgs.set(
        mapOf(
            "BITBUCKET_USR" to bitbucketUsr,
            "BITBUCKET_PSW" to bitbucketPwd,
            "GITHUB_USR" to githubUsr,
            "GITHUB_PSW" to githubPwd,
        )
    )
    authentications {
        create("docker-dev.bin.pega.io") {
            url.set("docker-dev.bin.pega.io")
            username.set(project.provider { project.findProperty("dockerRegistryUser")?.toString() })
            password.set(project.provider { project.findProperty("dockerRegistryPassword")?.toString() })
        }
    }

    // When running locally, tag image with tag "local" instead using the one generated by SmartVersion plugin,
    // so we can find proper image whe running "make integration-test-*" command
    if (isCI != "true") {
        dockerImage.imageTag.set("local")
    }
}

tasks.copyDockerDependencies.configure {
    from(rootProject.projectDir) {
        include("go.mod")
        include("go.sum")
        include("internal/**/*.go")
        include("internal/**/*.sql")
        include("cmd/background/**/*")
        include("cmd/middleware/*")
        include("apidocs/**/*")
    }
}