#Timeout to configure for component test stage of pipeline
#COMPONENT_TEST_TIMEOUT=180

#To enable whitesource scan for your service during pipeline run.
WHITESOURCE_SCAN_ENABLED=true

#To skip the End-to-End Deployment stage of the standard FNX service CI build pipeline
# 
# NOTE: This property should ONLY be set to true for projects that are using a separate
#       Out-of-Band pipeline to manually trigger deployments to the End to End testing
#       environment.  In most cases this means that a given service requires additional
#       validation that cannot be performed during the standard CI build validation stage prior
#       to determining whether or not a given build is fit for the End to End testing environment.
#
#       Please see the following link for more information regarding this property:
#
#       https://git.pega.io/projects/SQUID/repos/jenkins-service-pipeline-template/browse/templates/template/docs/cdModel.md
#

SKIP_INTEGRATION_TEST_IN_CI_BUILD=false
SKIP_INTEGRATION_TEST_IN_PR_BUILD=false

SKIP_END_TO_END_DEPLOY_IN_CI_BUILD=true
#SKIP_COMPONENT_TEST_IN_PR_BUILD=true
#SKIP_CONTRACT_TEST_IN_PR_BUILD=true
#SKIP_PROVIDER_VERIFICATION_STAGE_IN_PR_BUILD=true
#SKIP_MICRO_BENCHMARK_TEST_IN_PR_BUILD=true

####################################################################
# Build & Release notifications
#
# Get your webex space ids by:
#   1. going to https://teams.webex.com/spaces
#   2. click your space
#   3. Copy id from URL (https://teams.webex.com/spaces/a325fd20-aa9e-11e7-9e6b-05d8c751c9c6/chat)
# The space must have Squid Bot bot as a member
#
# For emails: Individuals should go through unhindered, but for Groups
# you will need to contact IT so that the Group is externally accessible
####################################################################

## Release announcements (comma separated list)
#RELEASE_ANNOUNCEMENT_WEBEX_SPACE_NOTIFICATION_LIST=fake-aa9e-11e7-9e6b-05d8c751c9c6,fake-c8de-11e9-9f72-43a4686805c2
#RELEASE_ANNOUNCEMENT_EMAIL_NOTIFICATION_LIST=Jane.Doe@pega.com,John.Doe@pega.com

## Build status notifications (comma separated list)
#BUILD_STATUS_WEBEX_SPACE_NOTIFICATION_LIST=fake-aa9e-11e7-9e6b-05d8c751c9c6
#BUILD_STATUS_EMAIL_NOTIFICATION_LIST=Jane.Doe@pega.com,John.Doe@pega.com

# Pass a label/name of executor in jenkins so that component tests are executed on it
# Read more about ec2 executors here https://agilestudio.pega.com/prweb/AgileStudio/app/agilestudio/doc/DOC-49523
#COMPONENT_TEST_NODE=ec2-instance-test




#CONTAINER_IMAGE=docker-release-local.bin.pega.io/java-11-with-build-tools:latest
#https://git.pega.io/projects/PCLD/repos/cloudbees-tools/browse/docker-builds/images/pega-cloud-kubernetes-base/README.md
CONTAINER_IMAGE=docker-release-local.bin.pega.io/pega-cloud-kubernetes-base:1.0-142
# Performance test node java configuration
PERF_TEST_NODE=blazemeter-taurus-with-java-17