{{- $cloudProvider := .Values.cloudProvider }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: genai-sax-config
  labels:
    {{- include "pegaTags" . | nindent 4 }}
spec:
  # SecretStoreRef defines which SecretStore to use when fetching the secret data
  secretStoreRef:
    {{- if eq $cloudProvider "gcp" }}
    name: project-cloudk-store
    {{- else  }}
    name: cloudk-store
    {{- end }}
    kind: ClusterSecretStore  # or SecretStore
  refreshInterval: "10m"
  target:
    name: genai-sax-config
  data:
    - secretKey: genai-sax-config
      remoteRef:
        key: '{{ .Values.saxClientDetailsArn }}'