---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mapping
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pegaTags" . | nindent 4 }}
data:
  mapping.yaml: |-
    models:
{{ range $path, $_ :=  .Files.Glob  "configuration/models/*.yaml" }}
{{- tpl ($.Files.Get $path) $ | trim | indent 6 }}
{{ end }}
    buddies:
{{ range $path, $_ :=  .Files.Glob  "configuration/buddies/*.yaml" }}
{{- tpl ($.Files.Get $path) $  | trim | indent 6 }}
{{ end }}
