// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	isolations "github.com/Pega-CloudEngineering/gen-ai-vector-store/internal/resources/isolations"
	mock "github.com/stretchr/testify/mock"
)

// MockIsoManager is an autogenerated mock type for the IsoManager type
type MockIsoManager struct {
	mock.Mock
}

type MockIsoManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIsoManager) EXPECT() *MockIsoManager_Expecter {
	return &MockIsoManager_Expecter{mock: &_m.Mock}
}

// CreateIsolation provides a mock function with given fields: ctx, isolationID, maxStorageSize, pdcEndpointURL
func (_m *MockIsoManager) CreateIsolation(ctx context.Context, isolationID string, maxStorageSize string, pdcEndpointURL string) error {
	ret := _m.Called(ctx, isolationID, maxStorageSize, pdcEndpointURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateIsolation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, isolationID, maxStorageSize, pdcEndpointURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIsoManager_CreateIsolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIsolation'
type MockIsoManager_CreateIsolation_Call struct {
	*mock.Call
}

// CreateIsolation is a helper method to define mock.On call
//   - ctx context.Context
//   - isolationID string
//   - maxStorageSize string
//   - pdcEndpointURL string
func (_e *MockIsoManager_Expecter) CreateIsolation(ctx interface{}, isolationID interface{}, maxStorageSize interface{}, pdcEndpointURL interface{}) *MockIsoManager_CreateIsolation_Call {
	return &MockIsoManager_CreateIsolation_Call{Call: _e.mock.On("CreateIsolation", ctx, isolationID, maxStorageSize, pdcEndpointURL)}
}

func (_c *MockIsoManager_CreateIsolation_Call) Run(run func(ctx context.Context, isolationID string, maxStorageSize string, pdcEndpointURL string)) *MockIsoManager_CreateIsolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIsoManager_CreateIsolation_Call) Return(_a0 error) *MockIsoManager_CreateIsolation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIsoManager_CreateIsolation_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockIsoManager_CreateIsolation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIsolation provides a mock function with given fields: ctx, isolationID
func (_m *MockIsoManager) DeleteIsolation(ctx context.Context, isolationID string) error {
	ret := _m.Called(ctx, isolationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIsolation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, isolationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIsoManager_DeleteIsolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIsolation'
type MockIsoManager_DeleteIsolation_Call struct {
	*mock.Call
}

// DeleteIsolation is a helper method to define mock.On call
//   - ctx context.Context
//   - isolationID string
func (_e *MockIsoManager_Expecter) DeleteIsolation(ctx interface{}, isolationID interface{}) *MockIsoManager_DeleteIsolation_Call {
	return &MockIsoManager_DeleteIsolation_Call{Call: _e.mock.On("DeleteIsolation", ctx, isolationID)}
}

func (_c *MockIsoManager_DeleteIsolation_Call) Run(run func(ctx context.Context, isolationID string)) *MockIsoManager_DeleteIsolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIsoManager_DeleteIsolation_Call) Return(_a0 error) *MockIsoManager_DeleteIsolation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIsoManager_DeleteIsolation_Call) RunAndReturn(run func(context.Context, string) error) *MockIsoManager_DeleteIsolation_Call {
	_c.Call.Return(run)
	return _c
}

// GetIsolation provides a mock function with given fields: ctx, isolationID
func (_m *MockIsoManager) GetIsolation(ctx context.Context, isolationID string) (*isolations.Details, error) {
	ret := _m.Called(ctx, isolationID)

	if len(ret) == 0 {
		panic("no return value specified for GetIsolation")
	}

	var r0 *isolations.Details
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*isolations.Details, error)); ok {
		return rf(ctx, isolationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *isolations.Details); ok {
		r0 = rf(ctx, isolationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*isolations.Details)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isolationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIsoManager_GetIsolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIsolation'
type MockIsoManager_GetIsolation_Call struct {
	*mock.Call
}

// GetIsolation is a helper method to define mock.On call
//   - ctx context.Context
//   - isolationID string
func (_e *MockIsoManager_Expecter) GetIsolation(ctx interface{}, isolationID interface{}) *MockIsoManager_GetIsolation_Call {
	return &MockIsoManager_GetIsolation_Call{Call: _e.mock.On("GetIsolation", ctx, isolationID)}
}

func (_c *MockIsoManager_GetIsolation_Call) Run(run func(ctx context.Context, isolationID string)) *MockIsoManager_GetIsolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIsoManager_GetIsolation_Call) Return(_a0 *isolations.Details, _a1 error) *MockIsoManager_GetIsolation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIsoManager_GetIsolation_Call) RunAndReturn(run func(context.Context, string) (*isolations.Details, error)) *MockIsoManager_GetIsolation_Call {
	_c.Call.Return(run)
	return _c
}

// GetIsolationProfiles provides a mock function with given fields: ctx, isolationID
func (_m *MockIsoManager) GetIsolationProfiles(ctx context.Context, isolationID string) ([]isolations.EmbeddingProfile, error) {
	ret := _m.Called(ctx, isolationID)

	if len(ret) == 0 {
		panic("no return value specified for GetIsolationProfiles")
	}

	var r0 []isolations.EmbeddingProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]isolations.EmbeddingProfile, error)); ok {
		return rf(ctx, isolationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []isolations.EmbeddingProfile); ok {
		r0 = rf(ctx, isolationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]isolations.EmbeddingProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isolationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIsoManager_GetIsolationProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIsolationProfiles'
type MockIsoManager_GetIsolationProfiles_Call struct {
	*mock.Call
}

// GetIsolationProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - isolationID string
func (_e *MockIsoManager_Expecter) GetIsolationProfiles(ctx interface{}, isolationID interface{}) *MockIsoManager_GetIsolationProfiles_Call {
	return &MockIsoManager_GetIsolationProfiles_Call{Call: _e.mock.On("GetIsolationProfiles", ctx, isolationID)}
}

func (_c *MockIsoManager_GetIsolationProfiles_Call) Run(run func(ctx context.Context, isolationID string)) *MockIsoManager_GetIsolationProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIsoManager_GetIsolationProfiles_Call) Return(_a0 []isolations.EmbeddingProfile, _a1 error) *MockIsoManager_GetIsolationProfiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIsoManager_GetIsolationProfiles_Call) RunAndReturn(run func(context.Context, string) ([]isolations.EmbeddingProfile, error)) *MockIsoManager_GetIsolationProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetIsolations provides a mock function with given fields: ctx
func (_m *MockIsoManager) GetIsolations(ctx context.Context) ([]*isolations.Details, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetIsolations")
	}

	var r0 []*isolations.Details
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*isolations.Details, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*isolations.Details); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*isolations.Details)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIsoManager_GetIsolations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIsolations'
type MockIsoManager_GetIsolations_Call struct {
	*mock.Call
}

// GetIsolations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIsoManager_Expecter) GetIsolations(ctx interface{}) *MockIsoManager_GetIsolations_Call {
	return &MockIsoManager_GetIsolations_Call{Call: _e.mock.On("GetIsolations", ctx)}
}

func (_c *MockIsoManager_GetIsolations_Call) Run(run func(ctx context.Context)) *MockIsoManager_GetIsolations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIsoManager_GetIsolations_Call) Return(_a0 []*isolations.Details, _a1 error) *MockIsoManager_GetIsolations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIsoManager_GetIsolations_Call) RunAndReturn(run func(context.Context) ([]*isolations.Details, error)) *MockIsoManager_GetIsolations_Call {
	_c.Call.Return(run)
	return _c
}

// IsolationExists provides a mock function with given fields: ctx, isolationID
func (_m *MockIsoManager) IsolationExists(ctx context.Context, isolationID string) (bool, error) {
	ret := _m.Called(ctx, isolationID)

	if len(ret) == 0 {
		panic("no return value specified for IsolationExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, isolationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, isolationID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isolationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIsoManager_IsolationExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsolationExists'
type MockIsoManager_IsolationExists_Call struct {
	*mock.Call
}

// IsolationExists is a helper method to define mock.On call
//   - ctx context.Context
//   - isolationID string
func (_e *MockIsoManager_Expecter) IsolationExists(ctx interface{}, isolationID interface{}) *MockIsoManager_IsolationExists_Call {
	return &MockIsoManager_IsolationExists_Call{Call: _e.mock.On("IsolationExists", ctx, isolationID)}
}

func (_c *MockIsoManager_IsolationExists_Call) Run(run func(ctx context.Context, isolationID string)) *MockIsoManager_IsolationExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIsoManager_IsolationExists_Call) Return(_a0 bool, _a1 error) *MockIsoManager_IsolationExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIsoManager_IsolationExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIsoManager_IsolationExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIsolation provides a mock function with given fields: ctx, isolationID, maxStorageSize, pdcEndpointURL
func (_m *MockIsoManager) UpdateIsolation(ctx context.Context, isolationID string, maxStorageSize string, pdcEndpointURL string) error {
	ret := _m.Called(ctx, isolationID, maxStorageSize, pdcEndpointURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIsolation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, isolationID, maxStorageSize, pdcEndpointURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIsoManager_UpdateIsolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIsolation'
type MockIsoManager_UpdateIsolation_Call struct {
	*mock.Call
}

// UpdateIsolation is a helper method to define mock.On call
//   - ctx context.Context
//   - isolationID string
//   - maxStorageSize string
//   - pdcEndpointURL string
func (_e *MockIsoManager_Expecter) UpdateIsolation(ctx interface{}, isolationID interface{}, maxStorageSize interface{}, pdcEndpointURL interface{}) *MockIsoManager_UpdateIsolation_Call {
	return &MockIsoManager_UpdateIsolation_Call{Call: _e.mock.On("UpdateIsolation", ctx, isolationID, maxStorageSize, pdcEndpointURL)}
}

func (_c *MockIsoManager_UpdateIsolation_Call) Run(run func(ctx context.Context, isolationID string, maxStorageSize string, pdcEndpointURL string)) *MockIsoManager_UpdateIsolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIsoManager_UpdateIsolation_Call) Return(_a0 error) *MockIsoManager_UpdateIsolation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIsoManager_UpdateIsolation_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockIsoManager_UpdateIsolation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIsoManager creates a new instance of MockIsoManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIsoManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIsoManager {
	mock := &MockIsoManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
