service-base:
  # name of this chart
  chartName: ${chartName}
  # version of this chart
  chartVersion: ${chartVersion}
  # name of the cluster in which service gets deployed
  ClusterName: "{{ .Values.ClusterName }}"
  # namespace of the service
  namespace: ${namespace}
  # When set to true , uses the private docker registry supported by k8s external secrets
  usePrivateDockerReg: true
  # When set to true, namespace wide resources like logging config maps , external secrets etc. are not created.
  skipCreateNamespace: false
  # Default true. Set to false to not create ingress resources so that the service is not reachable from outside the cluster i.e. The service will be reachable from cuttyhunk clients.
  createIngress: true
  global:
    provisioningTags:
      pega-service-id: PRD-7655
      pega-service-name: genai-hub-service
  pegaservices:
    ####################################################################
    # GenAI Hub Service deployment
    ####################################################################
    genai-hub-service: # name of an application within the service that will get its own docker container , e.g. your-service-name
      podDisruptionBudget: # Pod disruption budget should be enabled to limit concurrent disruptions to service and ensure smooth cluster maintenance
        enabled: true
        minAvailable: 1
      replicaCount: 2 # default number of containers to create (Not used when HPA used)
      applicationPort: 8080 # the port on which the application listens
      serviceIRSARole: "{{ .Values.serviceIRSARole }}"# The IAM role that container should use
      serviceType: http # service communication type, other available value could be for example 'grpc'
      createServiceAccount: true
      serviceAccountName: genai-hub-service
      image:
        repository: "{{ .Values.DockerImageRepo }}/${imageName}" # service docker image name
        tag: ${imageTag} # tag of the service docker image
      serviceRoot: / # The context root of your application
      serviceIngressPrefix: /${namespace}/ # Prefix for any traffic that should be forwarded from the public facing load balancer to your app
      egressRules:  "" # To enable Istio access for an external service(s) , provide list of external services to give access to (e.g. "www.service01.com:443,www.service02.com:80")
      isFrontendService: false # Default false. Set to true to allow the service to get traffic from external client browsers instead of from cuttyhunk clients or GOC.
      dnsName: "" # Configure this for a frontend service which wants to use host based routing instead of url path based routing.
      skipIngress: true # skip exposing service outside the cluster
      livenessProbePath: /health/liveness # The HTTP GET request path that should be invoked to test liveness
      readinessProbePath: /health/readiness # The HTTP GET request path that should be invoked to test readiness
      healthCheckPort: 8082 # Port on which liveness and readiness HTTP requests get invoked
      livenessProbeInitialDelay: 5 # Number of seconds after the container has started before liveness probe is initiated.
      readinessProbeInitialDelay: 15 # Number of seconds after the container has started before readiness probe is initiated.
      readinessProbeTimeout: 5 # Number of seconds after which the readiness probe times out
      livenessProbeTimeout: 5 # Number of seconds after which the liveness probe times out
      # An array of environment variables
      environmentTemplate: >
        - name: CONFIGURATION_FILE
          value: "/config/mapping.yaml"
        - name: MODEL_METADATA_PATH
          value: "/models-metadata/model-metadata.yaml"
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        - name: UAS_JWKS_URL
          value: "http://unified-authentication-service.uas:443/uas/api/v1/oauth2/jwks"
        - name: PLATFORM_TYPE
          value: "{{ .Values.platformType }}"
        - name: SAX_CONFIG_PATH
          value: "/genai-sax-config/genai-sax-config"
        - name: MONITORING_ENDPOINT
          value: http://genai-gateway-ops:80/v1/events
        - name: USE_GENAI_INFRA
          value: "{{ .Values.useGenAIInfra }}"
        - name: USE_AUTO_MAPPING
          value: "{{ .Values.useAutoMapping }}"        
        - name: MAPPING_ENDPOINT
          value: http://genai-gateway-ops:80/v1/mappings
        - name: DEMO_GCP_VERTEX_URL
          value: "{{ .Values.demoGcpVertexURL }}"
        - name: USE_VERTEXAI_INFRA
          value: "{{ .Values.useVertexAIInfra }}"
        - name: GENAI_URL
          value: "{{ .Values.genAIURL }}"
        - name: MODELS_DEFAULTS_ENDPOINT
          value: http://genai-gateway-ops:80/v1/models/defaults
        - name: DISPLAY_PREVIEW_MODELS
          value: "{{ .Values.displayPreviewModels }}"
        - name: SMART_MODEL_OVERRIDE
          value: "{{ .Values.smartModelOverride }}"
        - name: FAST_MODEL_OVERRIDE
          value: "{{ .Values.fastModelOverride }}"
        - name: PRO_MODEL_OVERRIDE
          value: "{{ .Values.proModelOverride }}"
        - name: ENABLED_PROVIDERS
          value: "{{ .Values.enabledProviders }}"
        - name: REQUEST_PROCESSING_COPYRIGHT_PROTECTION
          value: "{{ .Values.requestProcessingCopyrightProtection }}"
        - name: REQUEST_PROCESSING_OUTPUT_TOKENS_ADJUSTMENT_STRATEGY
          value: "{{ .Values.requestProcessingOutputTokensAdjustmentStrategy }}"
        - name: REQUEST_PROCESSING_OUTPUT_TOKENS_BASE_VALUE
          value: "{{ .Values.requestProcessingOutputTokensBaseValue }}"
        - name: REQUEST_PROCESSING_OUTPUT_TOKENS_ADJUSTMENT_FORCED 
          value: "{{ .Values.requestProcessingOutputTokensAdjustmentForced }}"
        - name: REQUEST_PROCESSING_OUTPUT_TOKENS_ADJUSTMENT_IN_STREAMING
          value: "{{ .Values.requestProcessingOutputTokensAdjustmentInStreaming }}"
        - name: REQUEST_PROCESSING_CACHE_SIZE
          value: "{{ .Values.requestProcessingCacheSize }}"
        - name: MODEL_TIMEOUT_SECONDS
          value: "{{ .Values.modelTimeoutSeconds }}"
        - name: ENABLE_PRO_MODEL_DEFAULT
          value: "{{ .Values.enableProModelDefault }}"
        - name: MODEL_CACHE_TTL
          value: "10m"
      # Monitoring annotations for New Relic
      # Refer https://git.pega.io/projects/CTRL/repos/service-base/browse/docs/options/monitoring_annotation_for_newrelic.md
      monitorPrometheusEp:
        enabled: true
        prometheusScrape: true
        prometheusPort: 8082
        prometheusPath: /metrics
      # Enable Logging for the namespace. Below logging configuration in form of fluent.conf will parse all the logs as json, merge exceptions in single line and send all the logs to CloudWatch.
      # Refer https://docs.fluentd.org/filter/parser for more info on parser filter plugin used.
      loggingConfigMap:
        fluent.conf: |-
          <filter **>
            @type parser
            key_name log
            reserve_data true
            hash_value_field log
            remove_key_name_field true
            emit_invalid_record_to_error false
            <parse>
              @type json
            </parse>
          </filter>
      # Specify resource (cpu and memory) requests and limits for service container
      container:
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 2
            memory: 2Gi
      # Enable horizontal pod autoscaling based on cpu utilization
      hpa:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60
      configMapMount:
        - mountName: mapping
          mountPath: /config
          configMapName: mapping
        - mountName: model-metadata
          mountPath: /models-metadata
          configMapName: model-metadata
      secretMount:
        - secretName: private-model-config
          mountPath: /private-model-config
          optional: true
        - secretName: genai-infra-config
          mountPath: /genai-infra-config/claude-3-haiku
          optional: true
        - secretName: genai-sax-config
          mountPath: /genai-sax-config
          optional: true

    genai-gateway-ops: # name of an application within the service that will get its own docker container , e.g. your-service-name
      isOpsService: true
      podDisruptionBudget: # Pod disruption budget should be enabled to limit concurrent disruptions to service and ensure smooth cluster maintenance
        enabled: false
      replicaCount: 1 # default number of containers to create (Not used when HPA used)
      applicationPort: 8081 # the port on which the application listens
      serviceType: http # service communication type, other available value could be for example 'grpc'
      serviceAccountName: genai-hub-service
      image:
        repository: "{{ .Values.DockerImageRepo }}/${opsImageName}" # service docker image name
        tag: ${opsImageTag} # tag of the service docker image
      serviceRoot: / # The context root of your application
      serviceIngressPrefix: /${namespace}-ops/ # Prefix for any traffic that should be forwarded from the public facing load balancer to your app
      egressRules:  "" # To enable Istio access for an external service(s) , provide list of external services to give access to (e.g. "www.service01.com:443,www.service02.com:80")
      dnsName: "" # Configure this for a frontend service which wants to use host based routing instead of url path based routing.
      skipIngress: false # skip exposing service outside the cluster
      livenessProbePath: /health/liveness # The HTTP GET request path that should be invoked to test liveness
      readinessProbePath: /health/readiness # The HTTP GET request path that should be invoked to test readiness
      healthCheckPort: 8082 # Port on which liveness and readiness HTTP requests get invoked
      livenessProbeInitialDelay: 5 # Number of seconds after the container has started before liveness probe is initiated.
      readinessProbeInitialDelay: 5 # Number of seconds after the container has started before readiness probe is initiated.
      readinessProbeTimeout: 5 # Number of seconds after which the readiness probe times out
      livenessProbeTimeout: 5 # Number of seconds after which the liveness probe times out
      # An array of environment variables
      environmentTemplate: >
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        - name: SAX_CELL
          value: "{{ .Values.saxCell }}"
        - name: STAGE_NAME
          value: "{{ .Values.stageName }}"
        - name: LLM_ACCOUNT_ID
          value: "{{ .Values.llmAccountID }}"
        - name: LLM_MODELS_REGION
          value: "{{ .Values.llmModelsRegion }}"
        - name: SAX_CONFIG_PATH
          value: "/genai-sax-config/genai-sax-config"
        - name: USE_GENAI_INFRA
          value: "{{ .Values.useGenAIInfra }}"
        - name: USE_AUTO_MAPPING
          value: "{{ .Values.useAutoMapping }}"
        - name: ENABLE_PRO_MODEL_DEFAULT
          value: "{{ .Values.enableProModelDefault }}"
      # Monitoring annotations for New Relic
      # Refer https://git.pega.io/projects/CTRL/repos/service-base/browse/docs/options/monitoring_annotation_for_newrelic.md
      monitorPrometheusEp:
        enabled: false
        prometheusScrape: false
        prometheusPort: 8082
        prometheusPath: /prometheus
      # Enable Logging for the namespace. Below logging configuration in form of fluent.conf will parse all the logs as json, merge exceptions in single line and send all the logs to CloudWatch.
      # Refer https://docs.fluentd.org/filter/parser for more info on parser filter plugin used.
      loggingConfigMap:
        fluent.conf: |-
          <filter **>
            @type parser
            key_name log
            reserve_data true
            hash_value_field log
            remove_key_name_field true
            emit_invalid_record_to_error false
            <parse>
              @type json
            </parse>
          </filter>
      # Specify resource (cpu and memory) requests and limits for service container
      container:
        resources:
          requests:
            cpu: 440m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 400Mi
      secretMount:
        - secretName: genai-sax-config
          mountPath: /genai-sax-config
          optional: true
