/*
 * This settings file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * In a single project build this file can be empty or even removed.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/3.4.1/userguide/multi_project_builds.html
 */

val artifactoryURL: String by settings
val artifactoryUser: String by settings
val artifactoryPassword: String by settings

pluginManagement {
    val artifactoryURL: String by settings
    val artifactoryUser: String by settings
    val artifactoryPassword: String by settings
    repositories {
        mavenLocal()
        maven {
            setUrl("${artifactoryURL}/repo2")
            credentials {
                setUsername("${artifactoryUser}")
                setPassword("${artifactoryPassword}")
            }
            metadataSources {
                ignoreGradleMetadataRedirection()
                mavenPom()
            }
        }
    }
    plugins {
        val sdeaOpinionatedPluginsVersion: String by settings
        val cloudServicesPluginsVersion: String by settings
        val goPluginVersion: String by settings
        //plugins to *actually* apply to the root project

        //SQuID Opinionated Plugins
        //All versions must be the same
        id("com.pega.release.cibuildversion") version sdeaOpinionatedPluginsVersion
        id("com.pega.veracode") version sdeaOpinionatedPluginsVersion
        id("com.pega.sce.publishing") version sdeaOpinionatedPluginsVersion
        id("com.pega.controlplane-deployment") version sdeaOpinionatedPluginsVersion
        id("com.pega.quality") version sdeaOpinionatedPluginsVersion
        id("com.pega.build-cache") version sdeaOpinionatedPluginsVersion
        id("com.pega.golang") version goPluginVersion
        id("com.pega.dockercli.image") version sdeaOpinionatedPluginsVersion
        id("com.pega.helmcli.helm") version sdeaOpinionatedPluginsVersion
        id("com.pega.terraform") version sdeaOpinionatedPluginsVersion
        id("com.pega.cloud.services.changelog") version cloudServicesPluginsVersion
        //End SQuID Opinionated Plugins

        //Cloud team's SCE plugin
        val pegaSceGradlePluginVersion: String by settings
        id("com.pega.sce.plugin") version pegaSceGradlePluginVersion
    }
}

plugins {
    id("com.pega.build-cache")
}

rootProject.name = "genai-hub-service"

include("distribution:genai-hub-service-sce")
include("distribution:genai-hub-service-docker")
include("distribution:genai-gateway-ops-docker")
include("distribution:genai-hub-service-helm")
include("distribution:sax-registration-sce")
include("distribution:sax-registration-terraform")
include("distribution:role-sce")
include("distribution:role-terraform")
include("distribution:genai-private-model-config-sce")
include("distribution:genai-private-model-config-terraform")
include("distribution:genai-private-model-externalsecret-sce")
include("distribution:genai-private-model-externalsecret-helm")
include("distribution:genai-awsbedrock-infra-sce")
include("distribution:genai-awsbedrock-infra-terraform")
include("distribution:genai-gcpvertex-host-sce")
include("distribution:genai-gcpvertex-host-terraform")
include("distribution:genai-gcpvertex-infra-sce")
include("distribution:genai-gcpvertex-infra-terraform")
include("distribution:sax-iam-oidc-provider-sce")
include("distribution:sax-iam-oidc-provider-terraform")
include("distribution:genai-defaults-sce")
include("distribution:genai-defaults-terraform")
include("distribution:product-catalog")